### ISSUE TITLE
License of midi2abc

### ISSUE THREAD

**Issue by basicmag** [marmooo/midi2abc#1]
Thank you for your great works!
I just would like to know what is the license of your midi2abc?

Thank you in advance.

**Comment by marmooo** [comment]
I decided to chose the MIT license in hopes of improving.

**Comment by basicmag** [comment]
Thank you for the reply and the license!

**Comment by GunGunGun** [comment]
> I decided to chose the MIT license in hopes of improving.

Thanks very much, so awesome!
